// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RankenClassSchedule.Models.DataLayer;

#nullable disable

namespace RankenClassSchedule.Migrations
{
    [DbContext(typeof(ClassScheduleContext))]
    [Migration("20251109235517_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RankenClassSchedule.Models.DomainModels.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<int>("DayId")
                        .HasColumnType("int");

                    b.Property<string>("MilitaryTime")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ClassId");

                    b.HasIndex("DayId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            ClassId = 1,
                            DayId = 1,
                            MilitaryTime = "0900",
                            Number = 101,
                            TeacherId = 1,
                            Title = "Introduction to Programming"
                        },
                        new
                        {
                            ClassId = 2,
                            DayId = 2,
                            MilitaryTime = "1100",
                            Number = 201,
                            TeacherId = 2,
                            Title = "Data Structures"
                        },
                        new
                        {
                            ClassId = 3,
                            DayId = 3,
                            MilitaryTime = "1300",
                            Number = 301,
                            TeacherId = 3,
                            Title = "Database Systems"
                        },
                        new
                        {
                            ClassId = 4,
                            DayId = 4,
                            MilitaryTime = "1500",
                            Number = 401,
                            TeacherId = 4,
                            Title = "Web Development"
                        },
                        new
                        {
                            ClassId = 5,
                            DayId = 5,
                            MilitaryTime = "1700",
                            Number = 501,
                            TeacherId = 5,
                            Title = "Software Engineering"
                        },
                        new
                        {
                            ClassId = 6,
                            DayId = 2,
                            MilitaryTime = "1000",
                            Number = 150,
                            TeacherId = 1,
                            Title = "Network Fundamentals"
                        },
                        new
                        {
                            ClassId = 7,
                            DayId = 3,
                            MilitaryTime = "1200",
                            Number = 250,
                            TeacherId = 2,
                            Title = "Operating Systems"
                        },
                        new
                        {
                            ClassId = 8,
                            DayId = 4,
                            MilitaryTime = "1400",
                            Number = 350,
                            TeacherId = 3,
                            Title = "Cybersecurity Basics"
                        });
                });

            modelBuilder.Entity("RankenClassSchedule.Models.DomainModels.Day", b =>
                {
                    b.Property<int>("DayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DayId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("DayId");

                    b.ToTable("Days");

                    b.HasData(
                        new
                        {
                            DayId = 1,
                            Name = "Monday"
                        },
                        new
                        {
                            DayId = 2,
                            Name = "Tuesday"
                        },
                        new
                        {
                            DayId = 3,
                            Name = "Wednesday"
                        },
                        new
                        {
                            DayId = 4,
                            Name = "Thursday"
                        },
                        new
                        {
                            DayId = 5,
                            Name = "Friday"
                        },
                        new
                        {
                            DayId = 6,
                            Name = "Saturday"
                        },
                        new
                        {
                            DayId = 7,
                            Name = "Sunday"
                        });
                });

            modelBuilder.Entity("RankenClassSchedule.Models.DomainModels.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TeacherId");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            TeacherId = 1,
                            FirstName = "Evan",
                            LastName = "Doe"
                        },
                        new
                        {
                            TeacherId = 2,
                            FirstName = "Jane",
                            LastName = "Smith"
                        },
                        new
                        {
                            TeacherId = 3,
                            FirstName = "Emily",
                            LastName = "Johnson"
                        },
                        new
                        {
                            TeacherId = 4,
                            FirstName = "Michael",
                            LastName = "Brown"
                        },
                        new
                        {
                            TeacherId = 5,
                            FirstName = "Sarah",
                            LastName = "Davis"
                        });
                });

            modelBuilder.Entity("RankenClassSchedule.Models.DomainModels.Class", b =>
                {
                    b.HasOne("RankenClassSchedule.Models.DomainModels.Day", "Day")
                        .WithMany("Classes")
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RankenClassSchedule.Models.DomainModels.Teacher", "Teacher")
                        .WithMany("Classes")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Day");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("RankenClassSchedule.Models.DomainModels.Day", b =>
                {
                    b.Navigation("Classes");
                });

            modelBuilder.Entity("RankenClassSchedule.Models.DomainModels.Teacher", b =>
                {
                    b.Navigation("Classes");
                });
#pragma warning restore 612, 618
        }
    }
}
